# Generated by Django 3.2.5 on 2021-10-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('iso', models.CharField(max_length=6)),
                ('aptos', models.PositiveIntegerField()),
                ('usuales', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.PositiveIntegerField()),
                ('desde', models.ManyToManyField(related_name='votos', to='votaciones.Departamento')),
                ('para', models.ManyToManyField(related_name='votos', to='votaciones.Partido')),
            ],
        ),
    ]
