# Generated by Django 3.2.5 on 2021-10-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='voto_en_blanco',
            field=models.BooleanField(default=False),
        ),
    ]
