# Generated by Django 3.2.5 on 2021-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0006_departamento_guardados'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
