# Generated by Django 3.2.5 on 2021-11-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0007_partido_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacion',
            name='desde',
        ),
        migrations.AddField(
            model_name='votacion',
            name='desde',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votaciones.departamento'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='votacion',
            name='para',
        ),
        migrations.AddField(
            model_name='votacion',
            name='para',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votaciones.partido'),
            preserve_default=False,
        ),
    ]
