# Generated by Django 3.2.5 on 2022-01-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0008_auto_20211101_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='usuales',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='iso',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
